version: "3"

services:
  proxy:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      tilt_network:
        ipv4_address: 172.50.0.2

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: tilt_frontend
    networks:
      tilt_network:
        ipv4_address: 172.50.0.3

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: tilt_backend
    restart: unless-stopped
    environment:
      - PORT=3000
      - LOG_LEVEL=debug
      - LOG_FILENAME=tilt.log
      - MAIL_HOST=maildev
      - MAIL_PORT=1025
      - MAIL_USERNAME=root@localhost
      - MAIL_PASSWORD=password
      - DATABASE_NAME=tilt
      - DATABASE_HOST=db
      - DATABASE_PASSWORD=wowsuchpassword
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=root
      - SECRET_JWT=wow_this_is_some_secure_password
    depends_on:
      - db
    networks:
      tilt_network:
        ipv4_address: 172.50.0.4

  db:
    image: mariadb:latest
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=wowsuchpassword
      - MYSQL_DATABASE=tilt
    ports:
      - 3306:3306
    networks:
      tilt_network:
        ipv4_address: 172.50.0.5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=wowsuchpassword
    ports:
      - 8081:80
    networks:
      tilt_network:
        ipv4_address: 172.50.0.6

  maildev:
    image: djfarrelly/maildev
    command: bin/maildev --incoming-user root@localhost --incoming-pass password --hide-extensions STARTTLS
    ports:
      - 8082:1080
      - "2525:1025"
    networks:
      tilt_network:
        ipv4_address: 172.50.0.7

networks:
  tilt_network:
    ipam:
      config:
        - subnet: 172.50.0.0/16
