name: Tests and push apps

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  style:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@master
    
    - name: Setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: install

    - name: prettier
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: prettier --check

    - name: lint
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: lint

  backend:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@master
    
    - name: Setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: install

    - name: test
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: backend::test
    
    - name: codecov
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: backend::codecov
    
  frontend:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@master
    
    - name: Setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: install

    - name: typecheck
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: frontend::typecheck

    - name: test
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: frontend::test
    
    - name: codecov
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: frontend::codecov

  build:
    runs-on: ubuntu-latest
    needs: [ style, backend, frontend ]
    steps:

    - name: Checkout repository
      uses: actions/checkout@master
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          hackaburg/tilt:latest
    